<%@ Page Title="" Language="C#" MasterPageFile="~/DenilC/image/FashionMasterPage.master" AutoEventWireup="true" CodeFile="FashionDefault.aspx.cs" Inherits="DenilC_image_FashionDefault" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    
    <style type="text/css">
        .auto-style1 {
            color: rgb(0, 0, 0);
        }
        .auto-style2 {
            color: #0066CC;
        }
        .auto-style3 {
            color: rgb(153, 102, 51);
        }
        .auto-style4 {
            color: rgb(102, 51, 0);
        }
    </style>
    
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server" >

    
    <div id="images" style="margin: 0px; padding: 5px 10px 0px 3px; float: left; width: 500px; text-align: left; z-index: 3; color: rgb(0, 0, 0); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <a "=" href="http://www.xsproductions.co.uk/images/image1.jpg" rel="thumbnail" style="margin: 0px; padding: 0px; font-family: arial; font-size: 12px; color: rgb(0, 255, 0); font-weight: bold; text-decoration: none;" title="Fashion Shows">
        <img border="0" src="http://www.xsproductions.co.uk/images/thumbs/image1.jpg" style="margin: 0px; padding: 0px; width: 104px; height: 78px;" /></a><span class="Apple-converted-space">&nbsp;</span><a "=" href="http://www.xsproductions.co.uk/images/image2.jpg" rel="thumbnail" style="margin: 0px; padding: 0px; font-family: arial; font-size: 12px; color: rgb(0, 255, 0); font-weight: bold; text-decoration: none;" title="Award Shows"><img border="0" src="http://www.xsproductions.co.uk/images/thumbs/image2.jpg" style="margin: 0px; padding: 0px; width: 104px; height: 78px;" /></a><span class="Apple-converted-space">&nbsp;</span><a "=" href="http://www.xsproductions.co.uk/images/image3.jpg" rel="thumbnail" style="margin: 0px; padding: 0px; font-family: arial; font-size: 12px; color: rgb(0, 255, 0); font-weight: bold; text-decoration: none;" title="Fashion Shows"><img border="0" src="http://www.xsproductions.co.uk/images/thumbs/image3.jpg" style="margin: 0px; padding: 0px; width: 104px; height: 78px;" /></a><span class="Apple-converted-space">&nbsp;</span><a "=" href="http://www.xsproductions.co.uk/images/image4.jpg" rel="thumbnail" style="margin: 0px; padding: 0px; font-family: arial; font-size: 12px; color: rgb(0, 255, 0); font-weight: bold; text-decoration: none;" title="Fashion Shows"><img border="0" src="http://www.xsproductions.co.uk/images/thumbs/image4.jpg" style="margin: 0px; padding: 0px; width: 104px; height: 78px;" /></a></div>
    <div id="heading" style="margin: 20px 0px 0px; padding: 0px 10px 0px 0px; float: left; width: 525px; text-align: left; z-index: 3; color: rgb(0, 0, 0); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <h1 style="margin: 0px; padding: 0px 0px 15px; font-family: arial; font-size: 20px; font-weight: normal;">Fashion Show Production, Event Management</h1>
    </div>
    <div id="text_1" class="normal" style="margin: 0px 52px 0px 0px; padding: 0px 10px 10px 0px; font-family: arial; font-size: 12px; color: rgb(255, 255, 255); font-weight: normal; text-decoration: none; float: left; width: 542px; background-image: url('http://www.xsproductions.co.uk/images/text_edges.jpg'); text-align: left; z-index: 3; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-repeat: no-repeat repeat;">
        <h2 style="margin: 0px; padding: 0px 0px 5px; font-family: arial; font-size: 14px; color: rgb(255, 255, 255); font-weight: bold; text-decoration: none;"><span style="margin: 0px; padding: 0px; " class="auto-style2"><span style="margin: 0px; padding: 0px; font-size: larger;"><em style="margin: 0px; padding: 0px;"><strong style="margin: 0px; padding: 0px;">WINNING AWARDS FOR OUR CLIENTS, INCREASING SALES AND FOOTFALL, PROVEN!!</strong></em></span></span></h2>
        <h2 style="margin: 0px; padding: 0px 0px 5px; font-family: arial; font-size: 14px; color: rgb(255, 255, 255); font-weight: bold; text-decoration: none;"><span style="margin: 0px; padding: 0px; " class="auto-style2"><span style="margin: 0px; padding: 0px; font-size: larger;"><em style="margin: 0px; padding: 0px;"><strong style="margin: 0px; padding: 0px;">PURPLE APPLE AWARD WINNER FOR &quot;DRIVING SALES&quot;, FESTIVAL PLACE STRICTLY GLAMOUR FASHION EVENT PRODUCED BY XS;</strong></em></span></span></h2>
        <p style="margin: 0px; padding: 0px;" class="auto-style4">
            &nbsp;</p>
        <p style="margin: 0px; padding: 0px;" class="auto-style4">
            XS Productions offer the complete Fashion Show and event production service, from concept to completion.</p>
        <span class="auto-style4">
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <p style="margin: 0px; padding: 0px;">
            We provide top models and dancers, show presenters, plus size models, child models, entertainment, celebrities..</p>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <p style="margin: 0px; padding: 0px;">
            Our choreographers are&nbsp; highly experienced ranging between Clothes Show Live, International Hair Shows, Shopping Centres and Television and London 2012 Olympics</p>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <p style="margin: 0px; padding: 0px;">
            Our stylists will take care of all aspects of retailer liaison and co-ordination of styles. Currently we are delighted to&nbsp;have on our team&nbsp;Wendy Elsmore and Ellie Pierce &nbsp;of This Morning TV show. Wendy &nbsp;brings Style Workshops and consultations to our shows. She also makes the shows look stunning as style is her business! Ellie worked with Wendy as style assistant and is also fashion expert for many QVC products</p>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <p style="margin: 0px; padding: 0px;">
            We provide all staging, lighting, sound, transport, crew and highly experienced lighting and sound operators.&nbsp;</p>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <p style="margin: 0px; padding: 0px;">
            We will also design and print all support material including stage branding if required.</p>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <p style="margin: 0px; padding: 0px;">
            Twenty &nbsp;years experience&nbsp; producing fashion shows in shopping centres and Trade Shows&nbsp;around the UK has placed us in a position to offer you an event second to none!</span></p>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <img id="plc_lt_zoneContent_pageplaceholder_pageplaceholder_lt_zoneMainContent_EditableImage_imgImage" alt="" class="header_image" src="http://img.com/Page-Images/imgworld_fashion.aspx" style="margin-bottom: 32px; color: rgb(81, 81, 81); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 14px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); border-width: 0px;" /><h2 style="padding: 0px; margin: 0px 0px 14px; font-weight: bold; font-size: 1.167em; color: rgb(0, 118, 192); text-transform: uppercase; font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 14px; orphans: auto; text-align: left; text-indent: 0px; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            EVENT MANAGEMENT &gt; FASHION</h2>
        <p style="padding: 0px; margin: 0px 0px 14px; color: rgb(81, 81, 81); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 14px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            IMG Fashion is the gateway to one of the world&#39;s most exclusive industries - from creation to the consumer.&nbsp;We offer solutions that seamlessly connect and associate fashion&#39;s key constituents and corporate brands using IMG&#39;s global expertise.</p>
        <p style="padding: 0px; margin: 0px 0px 14px; color: rgb(81, 81, 81); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 14px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            Each year, IMG Fashion&#39;s events attract the world&#39;s leading designers, editors, journalists, media outlets, retailers, fashion industry professionals, celebrities and style setters as well as the most beautiful models and supermodels.</p>
        <p style="padding: 0px; margin: 0px 0px 14px; color: rgb(81, 81, 81); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 14px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            &nbsp;</p>
        <p style="padding: 0px; margin: 0px 0px 14px; color: rgb(81, 81, 81); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 14px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            IMG’s global portfolio of fashion events includes:</p>
        <ul style="padding: 0px; margin: -14px 0px 14px; list-style: none; color: rgb(81, 81, 81); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 14px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://www.cameramoda.it/intro.php" style="color: rgb(0, 118, 192); text-decoration: none;">Milan Fashion Week Principal Sponsor Canon*</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://berlin.mbfashionweek.com/" style="color: rgb(0, 118, 192); text-decoration: none;">Mercedes-Benz Fashion Week Berlin</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://newyork.mbfashionweek.com/" style="color: rgb(0, 118, 192); text-decoration: none;">Mercedes-Benz Fashion Week (New York)</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://www.londonfashionweek.co.uk/" style="color: rgb(0, 118, 192); text-decoration: none;">London Fashion Week Principal Sponsor Vodafone*</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://istanbul.mbfashionweek.com/" style="color: rgb(0, 118, 192); text-decoration: none;">Mercedes-Benz Fashion Week Istanbul Presented by American Express</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://www.lakmefashionweek.co.in/" style="color: rgb(0, 118, 192); text-decoration: none;">Lakmé Fashion Week (Mumbai)</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://www.jfw.jp/en/" style="color: rgb(0, 118, 192); text-decoration: none;">Mercedes-Benz Fashion Week Tokyo*</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://www.worldmastercardfashionweek.com/" style="color: rgb(0, 118, 192); text-decoration: none;">World MasterCard Fashion Week (Toronto)</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://www.mercedesbenzfashionweekrussia.com/" style="color: rgb(0, 118, 192); text-decoration: none;">Mercedes-Benz Fashion Week Russia (Moscow)*</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://mbfashionweek.com.au/" style="color: rgb(0, 118, 192); text-decoration: none;">Mercedes-Benz Fashion Week Australia</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://miami.mbfashionweek.com/" style="color: rgb(0, 118, 192); text-decoration: none;">Mercedes-Benz Fashion Week Swim (Miami)</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://mbffsydney.com.au/homepage" style="color: rgb(0, 118, 192); text-decoration: none;">Mercedes-Benz Fashion Festival Sydney</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://www.fashionfringe.co.uk/" style="color: rgb(0, 118, 192); text-decoration: none;">Fashion Fringe (London)</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://www.mbfashiondays.ch/en/" style="color: rgb(0, 118, 192); text-decoration: none;">Mercedes-Benz Fashion Days Zurich</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://www.mercedes-benzstartup.com/" style="color: rgb(0, 118, 192); text-decoration: none;">Mercedes-Benz Start Up (Canada)</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://www.ihtconferences.com/luxury-2012.aspx" style="color: rgb(0, 118, 192); text-decoration: none;">IHT Luxury Conference*</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://www.britishfashionawards.com/" style="color: rgb(0, 118, 192); text-decoration: none;">British Fashion Awards*</a></li>
            <li style="padding: 0px 0px 0px 8px; margin: 0px; background-image: url(http://img.com/App_Themes/IMGWorld/images/bullet.jpg); background-position: 0px 6px; background-repeat: no-repeat no-repeat;"><a href="http://www.globalfashionawards.com/" style="color: rgb(0, 118, 192); text-decoration: none;">WGSN Global Fashion Awards*</a><p style="padding: 0px; margin: 0px 0px 14px;">
                &nbsp;</p>
            </li>
        </ul>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <div class="main" style="margin: 0px; padding: 0px; float: left; width: 640px; color: rgb(34, 34, 34); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 19.5px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        </div>
        <div class="main" style="margin: 0px; padding: 0px; float: left; width: 640px; color: rgb(34, 34, 34); font-family: Arial, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 19.5px; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            <div class="main_blocks" style="margin: 15px 0px 0px; padding: 0px;">
                <div id="container" style="margin: 0px; padding: 0px;">
                    <div id="block-holder" style="margin: 0px; padding: 0px;">
                        <div id="151" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl00_lionefourth" class="one_fourth news" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; font-size: 12px; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl00_hplNews" href="http://www.londonfashionweek.co.uk/news/623/Facts--Figures-AW14" style="margin: 0px; padding: 5px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; overflow: hidden;">
                                <h3 style="margin: 0px 0px 0.2em; padding: 0px; font-size: 19px; line-height: 1.1em; font-family: 'Avenir LT W01 55 Roman', Arial, Helvetica, sans-serif; font-weight: normal; color: rgb(230, 0, 0); text-transform: none; letter-spacing: 0px;">News</h3>
                                <p style="margin: 0px 0px 1.2em; padding: 0px; max-height: 127px; overflow: hidden;">
                                    <b style="margin: 0px; padding: 0px;">Facts &amp; Figures AW14</b><br style="margin: 0px; padding: 0px;" />
                                    At a press conference to open London Fashion Week Natalie Massenet, Chairman of the British Fashion ...</p>
                                </a>
                            </div>
                        </div>
                        <div id="344" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl01_lionefourth" class="one_fourth news" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; font-size: 12px; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl01_hplFixed" href="http://www.britishfashioncouncil.com/application_newgen.aspx" style="margin: 0px; padding: 5px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; overflow: hidden;">
                                <h3 style="margin: 0px 0px 0.2em; padding: 0px; font-size: 19px; line-height: 1.1em; font-family: 'Avenir LT W01 55 Roman', Arial, Helvetica, sans-serif; font-weight: normal; color: rgb(230, 0, 0); text-transform: none; letter-spacing: 0px;">NEWGEN Applications</h3>
                                <p style="margin: 0px 0px 1.2em; padding: 0px; max-height: 127px; overflow: hidden;">
                                    Applications for NEWGEN SS15 are now open – apply online here</p>
                                </a>
                            </div>
                        </div>
                        <div id="277" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl02_lionefourth" class="one_fourth news" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; font-size: 12px; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl02_hplFixed" href="http://www.londonfashionweek.co.uk/application_catwalk.aspx" style="margin: 0px; padding: 5px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; overflow: hidden;">
                                <h3 style="margin: 0px 0px 0.2em; padding: 0px; font-size: 19px; line-height: 1.1em; font-family: 'Avenir LT W01 55 Roman', Arial, Helvetica, sans-serif; font-weight: normal; color: rgb(230, 0, 0); text-transform: none; letter-spacing: 0px;">LFW Applications</h3>
                                <p style="margin: 0px 0px 1.2em; padding: 0px; max-height: 127px; overflow: hidden;">
                                    Applications to show on schedule at London Fashion Week SS15 are now open</p>
                                </a>
                            </div>
                        </div>
                        <div id="170" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl03_lionefourth" class="one_fourth news" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; font-size: 12px; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl03_hplFixed" href="http://www.londonfashionweek.co.uk/application_designer_showrooms.aspx" style="margin: 0px; padding: 5px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; overflow: hidden;">
                                <h3 style="margin: 0px 0px 0.2em; padding: 0px; font-size: 19px; line-height: 1.1em; font-family: 'Avenir LT W01 55 Roman', Arial, Helvetica, sans-serif; font-weight: normal; color: rgb(230, 0, 0); text-transform: none; letter-spacing: 0px;">Designer Showroom Applications</h3>
                                <p style="margin: 0px 0px 1.2em; padding: 0px; max-height: 127px; overflow: hidden;">
                                    Applications for the Designer Showrooms at London Fashion Week SS15 are now open</p>
                                </a>
                            </div>
                        </div>
                        <div id="340" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl04_lionefourth" class="one_fourth designer" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl04_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/designer/1054/Topshop-Unique" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl04_lblThumb" class="gallerythumb" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://www.londonfashionweek.co.uk/i.aspx?w=170&amp;i=/image_library/42/80/8573.jpg); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 10; opacity: 1; border: none; background-position: 50% 0%; background-repeat: initial initial;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl04_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;">Topshop Unique</span></a></div>
                        </div>
                        <div id="160" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl05_lionefourth" class="one_fourth news" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; font-size: 12px; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl05_hplNews" href="http://www.londonfashionweek.co.uk/news/621/WeTransfer--British-Fashion-C" style="margin: 0px; padding: 5px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; overflow: hidden;">
                                <h3 style="margin: 0px 0px 0.2em; padding: 0px; font-size: 19px; line-height: 1.1em; font-family: 'Avenir LT W01 55 Roman', Arial, Helvetica, sans-serif; font-weight: normal; color: rgb(230, 0, 0); text-transform: none; letter-spacing: 0px;">News</h3>
                                <p style="margin: 0px 0px 1.2em; padding: 0px; max-height: 127px; overflow: hidden;">
                                    <b style="margin: 0px; padding: 0px;">WeTransfer &amp; British Fashion Council Collaboration for LFW</b><br style="margin: 0px; padding: 0px;" />
                                    During London Fashion Week, free file-sharing service, WeTransfer, will showcase the work of leading...</p>
                                </a>
                            </div>
                        </div>
                        <div id="164" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl06_lionefourth" class="one_fourth event" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl06_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/event/1246/Vodafone-London-Fashion-Weeken" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl06_lblThumb" class="gallerythumb eventicon" style="margin: 0px; padding: 5px; background-image: url(http://www.britishfashioncouncil.com/i.aspx?h=140&amp;i=/uploads/media/1041/54693.jpg); bottom: 0px; display: block; height: 145px; position: absolute; right: 0px; width: 145px; z-index: 10; overflow: hidden; color: rgb(235, 235, 235); left: 0px; top: 0px; opacity: 1; border: none; background-position: 50% 0%; background-repeat: initial initial;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl06_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;"></span>
                                <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl06_pnleventicon" class="eventicon" style="background: url('http://www.londonfashionweek.co.uk/images/eventsicon.png') no-repeat no-repeat 100% 100%; margin: 0px; padding: 0px; bottom: 0px; display: block; height: 40px; position: absolute; right: 0px; width: 40px; z-index: 9999;">
                                </div>
                                </a>
                            </div>
                        </div>
                        <div id="5" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl07_lionefourth" class="one_fourth catwalkvideo" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl07_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/highlights.aspx?SeasonID=47&amp;Seasonday=2014-2-18&amp;homepagevideoid=871" onclick="playVideo(871);return false;" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl07_lblPlayButton" class="gallerythumb playbutton" style="margin: -6px 0px 0px -6px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://www.londonfashionweek.co.uk/images/video-play.png); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 11; opacity: 1; border: none; background-position: 50% 50%; background-repeat: no-repeat no-repeat;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl07_lblThumb" class="gallerythumb" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://videos.rightster.com//rightster/000001/encodes/images/5141596d057f3bc43c6b45f3ccd652c1_53035302_640x360.jpg); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 10; opacity: 1; border: none; background-position: 50% 50%; background-repeat: initial initial;"></span><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl07_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;">
                                </span></a>
                            </div>
                        </div>
                        <div id="341" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl08_lionefourth" class="one_fourth designer" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl08_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/designer/14/Amanda-Wakeley" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl08_lblThumb" class="gallerythumb" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://www.londonfashionweek.co.uk/i.aspx?w=170&amp;i=/image_library/42/80/9239.jpg); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 10; opacity: 1; border: none; background-position: 50% 0%; background-repeat: initial initial;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl08_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;">Amanda Wakeley</span></a></div>
                        </div>
                        <div id="7" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl09_lionefourth" class="one_fourth catwalkvideo" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl09_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/highlights.aspx?SeasonID=47&amp;Seasonday=2014-2-18&amp;homepagevideoid=896" onclick="playVideo(896);return false;" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl09_lblPlayButton" class="gallerythumb playbutton" style="margin: -6px 0px 0px -6px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://www.londonfashionweek.co.uk/images/video-play.png); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 11; opacity: 1; border: none; background-position: 50% 50%; background-repeat: no-repeat no-repeat;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl09_lblThumb" class="gallerythumb" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://videos.rightster.com//rightster/000001/encodes/images/7fc319764a0acccc4fac8b4aad1e0771_5303a44f_640x360.jpg); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 10; opacity: 1; border: none; background-position: 50% 50%; background-repeat: initial initial;"></span><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl09_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;">
                                </span></a>
                            </div>
                        </div>
                        <div id="342" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl10_lionefourth" class="one_fourth designer" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl10_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/designer/101/Emilio-de-la-Morena" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl10_lblThumb" class="gallerythumb" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://www.londonfashionweek.co.uk/i.aspx?w=170&amp;i=/image_library/42/80/7447.jpg); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 10; opacity: 1; border: none; background-position: 50% 0%; background-repeat: initial initial;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl10_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;">Emilio de la Morena</span></a></div>
                        </div>
                        <div id="19" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl11_lionefourth" class="one_fourth catwalkgallery" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl11_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/designers_catwalk_overlay.aspx?SeasonID=47&amp;Seasonday=2014-2-18&amp;DesignerID=2400" onclick="ShowGallery(this.href,'Collection',800,600);return false" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl11_lblThumb" class="gallerythumb" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://www.londonfashionweek.co.uk/uploads/collections/2400/47/1/221906.jpg); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 10; opacity: 1; border: none; background-position: 50% 0%; background-repeat: initial initial;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl11_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;">SIMONGAO</span></a></div>
                        </div>
                        <div id="6" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl12_lionefourth" class="one_fourth catwalkgallery" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl12_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/designers_catwalk_overlay.aspx?SeasonID=47&amp;Seasonday=2014-2-18&amp;DesignerID=2230" onclick="ShowGallery(this.href,'Collection',800,600);return false" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl12_lblThumb" class="gallerythumb" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://www.londonfashionweek.co.uk/uploads/collections/2230/47/1/221796.jpg); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 10; opacity: 1; border: none; background-position: 50% 0%; background-repeat: initial initial;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl12_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;">Barbara Casasola</span></a></div>
                        </div>
                        <div id="9" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl13_lionefourth" class="one_fourth catwalkvideo" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl13_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/highlights.aspx?SeasonID=47&amp;Seasonday=2014-2-18&amp;homepagevideoid=857" onclick="playVideo(857);return false;" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl13_lblPlayButton" class="gallerythumb playbutton" style="margin: -6px 0px 0px -6px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://www.londonfashionweek.co.uk/images/video-play.png); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 11; opacity: 1; border: none; background-position: 50% 50%; background-repeat: no-repeat no-repeat;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl13_lblThumb" class="gallerythumb" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://videos.rightster.com//rightster/000001/encodes/images/ef4663f218697c322be05ee18068a0ca_53038f22_640x360.jpg); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 10; opacity: 1; border: none; background-position: 50% 50%; background-repeat: initial initial;"></span><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl13_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;">
                                </span></a>
                            </div>
                        </div>
                        <div id="339" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl14_lionefourth" class="one_fourth designer" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl14_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/designer/1342/Topman-Design" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl14_lblThumb" class="gallerythumb" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://www.londonfashionweek.co.uk/i.aspx?w=170&amp;i=/image_library/42/80/9114.jpg); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 10; opacity: 1; border: none; background-position: 50% 0%; background-repeat: initial initial;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl14_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;">Topman Design</span></a></div>
                        </div>
                        <div id="158" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl15_lionefourth" class="one_fourth news" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; font-size: 12px; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl15_hplNews" href="http://www.londonfashionweek.co.uk/news/622/Whats-On-at-London-Fashion-We" style="margin: 0px; padding: 5px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; overflow: hidden;">
                                <h3 style="margin: 0px 0px 0.2em; padding: 0px; font-size: 19px; line-height: 1.1em; font-family: 'Avenir LT W01 55 Roman', Arial, Helvetica, sans-serif; font-weight: normal; color: rgb(230, 0, 0); text-transform: none; letter-spacing: 0px;">News</h3>
                                <p style="margin: 0px 0px 1.2em; padding: 0px; max-height: 127px; overflow: hidden;">
                                    <b style="margin: 0px; padding: 0px;">What&#39;s On at London Fashion Week AW14<span class="Apple-converted-space">&nbsp;</span></b><br style="margin: 0px; padding: 0px;" />
                                    London Fashion Week, 14-18 February is set to showcase some of the world’s leading fashion tal...</p>
                                </a>
                            </div>
                        </div>
                        <div id="10" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl16_lionefourth" class="one_fourth catwalkgallery" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl16_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/designers_catwalk_overlay.aspx?SeasonID=47&amp;Seasonday=2014-2-18&amp;DesignerID=1047" onclick="ShowGallery(this.href,'Collection',800,600);return false" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl16_lblThumb" class="gallerythumb" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://www.londonfashionweek.co.uk/uploads/collections/1047/47/1/221830.jpg); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 10; opacity: 1; border: none; background-position: 50% 0%; background-repeat: initial initial;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl16_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;">KTZ</span></a></div>
                        </div>
                        <div id="152" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl17_lionefourth" class="one_fourth event" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl17_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/event/1256/Models-Own-Image-The-Ethics-" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl17_lblThumb" class="gallerythumb eventicon" style="margin: 0px; padding: 5px; background-image: url(http://www.britishfashioncouncil.com/i.aspx?h=140&amp;i=/uploads/media/1041/59673.jpg); bottom: 0px; display: block; height: 145px; position: absolute; right: 0px; width: 145px; z-index: 10; overflow: hidden; color: rgb(235, 235, 235); left: 0px; top: 0px; opacity: 1; border: none; background-position: 50% 0%; background-repeat: initial initial;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl17_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;"></span>
                                <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl17_pnleventicon" class="eventicon" style="background: url('http://www.londonfashionweek.co.uk/images/eventsicon.png') no-repeat no-repeat 100% 100%; margin: 0px; padding: 0px; bottom: 0px; display: block; height: 40px; position: absolute; right: 0px; width: 40px; z-index: 9999;">
                                </div>
                                </a>
                            </div>
                        </div>
                        <div id="13" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl18_lionefourth" class="one_fourth catwalkgallery" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl18_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/designers_catwalk_overlay.aspx?SeasonID=47&amp;Seasonday=2014-2-18&amp;DesignerID=215" onclick="ShowGallery(this.href,'Collection',800,600);return false" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl18_lblThumb" class="gallerythumb" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://www.londonfashionweek.co.uk/uploads/collections/215/47/1/221866.jpg); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 10; opacity: 1; border: none; background-position: 50% 0%; background-repeat: initial initial;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl18_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;">Meadham Kirchhoff</span></a></div>
                        </div>
                        <div id="338" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl19_lionefourth" class="one_fourth designer" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl19_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/designer/2093/Mich-Dulce" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl19_lblThumb" class="gallerythumb" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://www.londonfashionweek.co.uk/i.aspx?w=170&amp;i=/image_library/42/80/8060.jpg); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 10; opacity: 1; border: none; background-position: 50% 0%; background-repeat: initial initial;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl19_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;">Mich Dulce</span></a></div>
                        </div>
                        <div id="11" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl20_lionefourth" class="one_fourth catwalkvideo" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl20_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/highlights.aspx?SeasonID=47&amp;Seasonday=2014-2-18&amp;homepagevideoid=842" onclick="playVideo(842);return false;" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl20_lblPlayButton" class="gallerythumb playbutton" style="margin: -6px 0px 0px -6px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://www.londonfashionweek.co.uk/images/video-play.png); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 11; opacity: 1; border: none; background-position: 50% 50%; background-repeat: no-repeat no-repeat;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl20_lblThumb" class="gallerythumb" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://videos.rightster.com//rightster/000001/encodes/images/f6a829796b8042479ea1e94fc1b8a891_53039dc3_640x360.jpg); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 10; opacity: 1; border: none; background-position: 50% 50%; background-repeat: initial initial;"></span><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl20_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;">
                                </span></a>
                            </div>
                        </div>
                        <div id="168" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl21_lionefourth" class="one_fourth event" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl21_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/event/1208/Marks--Spencer-Best-of-Britis" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl21_lblThumb" class="gallerythumb eventicon" style="margin: 0px; padding: 5px; background-image: url(http://www.britishfashioncouncil.com/i.aspx?h=140&amp;i=/uploads/media/1041/58266.jpg); bottom: 0px; display: block; height: 145px; position: absolute; right: 0px; width: 145px; z-index: 10; overflow: hidden; color: rgb(235, 235, 235); left: 0px; top: 0px; opacity: 1; border: none; background-position: 50% 0%; background-repeat: initial initial;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl21_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;"></span>
                                <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl21_pnleventicon" class="eventicon" style="background: url('http://www.londonfashionweek.co.uk/images/eventsicon.png') no-repeat no-repeat 100% 100%; margin: 0px; padding: 0px; bottom: 0px; display: block; height: 40px; position: absolute; right: 0px; width: 40px; z-index: 9999;">
                                </div>
                                </a>
                            </div>
                        </div>
                        <div id="275" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl22_lionefourth" class="one_fourth event" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl22_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/event/983/The-North-Circular-Polar-Launc" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl22_lblThumb" class="gallerythumb eventicon" style="margin: 0px; padding: 5px; background-image: url(http://www.britishfashioncouncil.com/i.aspx?h=140&amp;i=/uploads/media/1041/52405.jpg); bottom: 0px; display: block; height: 145px; position: absolute; right: 0px; width: 145px; z-index: 10; overflow: hidden; color: rgb(235, 235, 235); left: 0px; top: 0px; opacity: 1; border: none; background-position: 50% 0%; background-repeat: initial initial;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl22_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;">Raising awareness of Greenpeace&#39;s #savethearctic campaign</span><div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl22_pnleventicon" class="eventicon" style="background: url('http://www.londonfashionweek.co.uk/images/eventsicon.png') no-repeat no-repeat 100% 100%; margin: 0px; padding: 0px; bottom: 0px; display: block; height: 40px; position: absolute; right: 0px; width: 40px; z-index: 9999;">
                                </div>
                                </a>
                            </div>
                        </div>
                        <div id="21" style="margin: 0px; padding: 0px;">
                            <div id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl23_lionefourth" class="one_fourth catwalkgallery" style="margin: 0px 13px 13px 0px; padding: 0px; width: 145px; height: 145px; float: left; background-color: rgb(238, 238, 238); border-bottom-style: none; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                                <a id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl23_hyp" class="gallerydescthumb " href="http://www.londonfashionweek.co.uk/designers_catwalk_overlay.aspx?SeasonID=47&amp;Seasonday=2014-2-18&amp;DesignerID=1120" onclick="ShowGallery(this.href,'Collection',800,600);return false" style="margin: 0px; padding: 0px; outline: none; color: rgb(0, 0, 0); transition: color; -webkit-transition: color; text-decoration: none; width: 145px; height: 145px; display: block; position: relative; z-index: 1;"><span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl23_lblThumb" class="gallerythumb" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: url(http://www.londonfashionweek.co.uk/uploads/collections/1120/47/1/221460.jpg); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 10; opacity: 1; border: none; background-position: 50% 0%; background-repeat: initial initial;"></span>
                                <span id="ctl00_PageHolder_ContentHolder_Main_ctl00_ctl00_rptBlocks_ctl23_lblDesc" class="gallerydesc" style="margin: 0px; padding: 5px; height: 145px; overflow: hidden; width: 145px; background-image: none; background-attachment: scroll; background-color: rgba(0, 0, 0, 0.701961); color: rgb(235, 235, 235); display: block; left: 0px; position: absolute; top: 0px; z-index: 12; opacity: 0; border: medium none; background-position: 0px 0px; background-repeat: repeat repeat;">Zoë Jordan</span></a></div>
                        </div>
                    </div>
                    <div class="clear" style="margin: 0px; padding: 0px; clear: both;">
                    </div>
                    <div class="loadmore" style="margin: 0px 0px 10px; padding: 0px; width: 620px; height: 30px; text-align: center; font-size: 18px; line-height: 30px; background-color: rgb(238, 238, 238); background-position: initial initial; background-repeat: initial initial;">
                        <a class="loadmore-link" href="javascript:void(0);" style="margin: 0px; padding: 0px; outline: none; color: rgb(25, 25, 25); transition: color; -webkit-transition: color; text-decoration: none;">More...</a></div>
                </div>
            </div>
        </div>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <div class="title" style="margin: 0px 0px 31px; overflow: hidden; display: table; color: rgb(116, 116, 116); font-family: 'PT Sans', Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            <h3 style="display: table-cell; white-space: pre; float: left; padding: 0px 8px 0px 0px !important; margin: 0px !important; font-family: MuseoSlab500Regular, arial, helvetica, sans-serif; color: rgb(51, 51, 51) !important; font-weight: normal; font-size: 16px !important; line-height: 24px !important;">Latest News</h3>
            <div class="title-sep-container" style="display: table-cell; vertical-align: middle; width: 510px; position: relative; height: 6px;">
                <div class="title-sep" style="display: block; border-top-width: 1px; border-top-style: solid; border-color: rgb(224, 222, 222) !important; border-bottom-width: 1px; border-bottom-style: solid; width: 510px; position: relative; height: 6px;">
                </div>
            </div>
        </div>
        <div class="avada-container layout-thumbnails-on-side layout-columns-3" style="color: rgb(116, 116, 116); font-family: 'PT Sans', Arial, Helvetica, sans-serif; font-size: 13px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 21px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
            <section class="columns columns-3" style="overflow: hidden; margin: 0px 0px 50px; width: 614.125px;">
                <div class="holder">
                    <article class="col clearfix" style="float: left; width: 193px; margin: 0px 16.375px 20px 0px; clear: both;">
                        <div class="flexslider floated-post-slideshow" style="margin: 0px 20px 0px 0px; padding: 0px; background-color: rgb(255, 255, 255); position: relative; zoom: 1; width: 144px; float: left; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                            <ul class="slides" style="margin: 0px; padding: 0px; list-style: none; z-index: 1000; zoom: 1; display: block;">
                                <li style="display: list-item; -webkit-backface-visibility: hidden;"><a href="http://www.lakmefashionweek.co.in/lfw-sr-14/lakme-absolute-presented-a-scintillating-collection-by-rajesh-pratap-singh-at-the-grand-finale-during-lakme-fashion-week-summerresort-2014/" rel="" style="text-decoration: none; color: rgb(51, 51, 51) !important;">
                                    <img alt="Lakme Absolute Presented a Scintillating Collection by Rajesh Pratap Singh at The Grand Finale During Lakme Fashion Week Summer/Resort 2014" src="http://www.lakmefashionweek.co.in/wp-content/uploads/2014/03/rps-2-feat1-460x295.jpg" style="border-style: none; vertical-align: top; max-width: 100%; height: auto; width: 144px; display: block;" /></a></li>
                            </ul>
                        </div>
                        <div class="recent-posts-content">
                            <h4 style="margin: 0px 0px 3px; font-family: MuseoSlab500Regular, arial, helvetica, sans-serif; color: rgb(51, 51, 51) !important; font-weight: normal; font-size: 13px !important; line-height: 20px !important;"><a href="http://www.lakmefashionweek.co.in/lfw-sr-14/lakme-absolute-presented-a-scintillating-collection-by-rajesh-pratap-singh-at-the-grand-finale-during-lakme-fashion-week-summerresort-2014/" style="text-decoration: none; color: rgb(51, 51, 51) !important;">Lakme Absolute Presented a Scintillating Collection by Rajesh Pratap Singh at The Grand Finale During Lakme Fashion Week Summer/Resort 2014</a></h4>
                        </div>
                    </article>
                    <article class="col clearfix" style="float: left; width: 193px; margin: 0px 16.375px 20px 0px;">
                        <div class="flexslider floated-post-slideshow" style="margin: 0px 20px 0px 0px; padding: 0px; background-color: rgb(255, 255, 255); position: relative; zoom: 1; width: 144px; float: left; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                            <ul class="slides" style="margin: 0px; padding: 0px; list-style: none; z-index: 1000; zoom: 1; display: block;">
                                <li style="display: list-item; -webkit-backface-visibility: hidden;"><a href="http://www.lakmefashionweek.co.in/lfw-sr-14/ami-grewal-junelia-aguiar-chandler-gave-fashionable-directions-at-jabong-stage-during-lakme-fashion-week-summerresort-2014/" rel="" style="text-decoration: none; color: rgb(51, 51, 51) !important;">
                                    <img alt="Ami Grewal &amp; Junelia Aguiar Chandler Gave Fashionable Directions at Jabong Stage During Lakme Fashion Week Summer/Resort 2014" src="http://www.lakmefashionweek.co.in/wp-content/uploads/2014/03/rrja-feat-460x295.jpg" style="border-style: none; vertical-align: top; max-width: 100%; height: auto; width: 144px; display: block;" /></a></li>
                            </ul>
                        </div>
                        <div class="recent-posts-content">
                            <h4 style="margin: 0px 0px 3px; font-family: MuseoSlab500Regular, arial, helvetica, sans-serif; color: rgb(51, 51, 51) !important; font-weight: normal; font-size: 13px !important; line-height: 20px !important;"><a href="http://www.lakmefashionweek.co.in/lfw-sr-14/ami-grewal-junelia-aguiar-chandler-gave-fashionable-directions-at-jabong-stage-during-lakme-fashion-week-summerresort-2014/" style="text-decoration: none; color: rgb(51, 51, 51) !important;">Ami Grewal &amp; Junelia Aguiar Chandler Gave Fashionable Directions at Jabong Stage During Lakme Fashion Week Summer/Resort 2014</a></h4>
                        </div>
                    </article>
                    <article class="col clearfix" style="float: left; width: 193px; margin: 0px 0px 20px;">
                        <div class="flexslider floated-post-slideshow" style="margin: 0px 20px 0px 0px; padding: 0px; background-color: rgb(255, 255, 255); position: relative; zoom: 1; width: 144px; float: left; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                            <ul class="slides" style="margin: 0px; padding: 0px; list-style: none; z-index: 1000; zoom: 1; display: block;">
                                <li style="display: list-item; -webkit-backface-visibility: hidden;"><a href="http://www.lakmefashionweek.co.in/lfw-sr-14/priyanka-chopra-was-the-stunning-showstopper-for-the-neeta-lulla-colourful-diffusion-show-presented-by-reliance-trends-at-lakme-fashion-week-summerresort-2014/" rel="" style="text-decoration: none; color: rgb(51, 51, 51) !important;">
                                    <img alt="Priyanka Chopra Was The Stunning Showstopper For The Neeta Lulla Colourful Diffusion Show Presented By Reliance Trends At Lakmé Fashion Week Summer/Resort 2014" src="http://www.lakmefashionweek.co.in/wp-content/uploads/2014/03/sad-460x295.jpg" style="border-style: none; vertical-align: top; max-width: 100%; height: auto; width: 144px; display: block;" /></a></li>
                            </ul>
                        </div>
                        <div class="recent-posts-content">
                            <h4 style="margin: 0px 0px 3px; font-family: MuseoSlab500Regular, arial, helvetica, sans-serif; color: rgb(51, 51, 51) !important; font-weight: normal; font-size: 13px !important; line-height: 20px !important;"><a href="http://www.lakmefashionweek.co.in/lfw-sr-14/priyanka-chopra-was-the-stunning-showstopper-for-the-neeta-lulla-colourful-diffusion-show-presented-by-reliance-trends-at-lakme-fashion-week-summerresort-2014/" style="text-decoration: none; color: rgb(51, 51, 51) !important;">Priyanka Chopra Was The Stunning Showstopper For The Neeta Lulla Colourful Diffusion Show Presented By Reliance Trends At Lakmé Fashion Week Summer/Resort 2014</a></h4>
                        </div>
                    </article>
                    <article class="col clearfix" style="float: left; width: 193px; margin: 0px 16.375px 20px 0px; clear: both;">
                        <div class="flexslider floated-post-slideshow" style="margin: 0px 20px 0px 0px; padding: 0px; background-color: rgb(255, 255, 255); position: relative; zoom: 1; width: 144px; float: left; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                            <ul class="slides" style="margin: 0px; padding: 0px; list-style: none; z-index: 1000; zoom: 1; display: block;">
                                <li style="display: list-item; -webkit-backface-visibility: hidden;"><a href="http://www.lakmefashionweek.co.in/lfw-sr-14/little-shilpas-unconventional-fashion-created-a-great-stir-at-jabong-stage-during-lakme-fashion-week-summerresort-2014/" rel="" style="text-decoration: none; color: rgb(51, 51, 51) !important;">
                                    <img alt="Little Shilpa’s Unconventional Fashion Created a Great Stir at Jabong Stage During Lakme Fashion Week Summer/Resort 2014" src="http://www.lakmefashionweek.co.in/wp-content/uploads/2014/03/ls-feat-460x295.jpg" style="border-style: none; vertical-align: top; max-width: 100%; height: auto; width: 144px; display: block;" /></a></li>
                            </ul>
                        </div>
                        <div class="recent-posts-content">
                            <h4 style="margin: 0px 0px 3px; font-family: MuseoSlab500Regular, arial, helvetica, sans-serif; color: rgb(51, 51, 51) !important; font-weight: normal; font-size: 13px !important; line-height: 20px !important;"><a href="http://www.lakmefashionweek.co.in/lfw-sr-14/little-shilpas-unconventional-fashion-created-a-great-stir-at-jabong-stage-during-lakme-fashion-week-summerresort-2014/" style="text-decoration: none; color: rgb(51, 51, 51) !important;">Little Shilpa’s Unconventional Fashion Created a Great Stir at Jabong Stage During Lakme Fashion Week Summer/Resort 2014</a></h4>
                        </div>
                    </article>
                    <article class="col clearfix" style="float: left; width: 193px; margin: 0px 16.375px 20px 0px;">
                        <div class="flexslider floated-post-slideshow" style="margin: 0px 20px 0px 0px; padding: 0px; background-color: rgb(255, 255, 255); position: relative; zoom: 1; width: 144px; float: left; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                            <ul class="slides" style="margin: 0px; padding: 0px; list-style: none; z-index: 1000; zoom: 1; display: block;">
                                <li style="display: list-item; -webkit-backface-visibility: hidden;"><a href="http://www.lakmefashionweek.co.in/lfw-sr-14/the-stylecracker-hood-event-was-a-creative-fashion-platform-at-the-pavilion-during-lakme-fashion-week-summerresort-2014/" rel="" style="text-decoration: none; color: rgb(51, 51, 51) !important;">
                                    <img alt="The Stylecracker Hood Event was a Creative Fashion Platform at the Pavilion During Lakme Fashion Week Summer/Resort 2014" src="http://www.lakmefashionweek.co.in/wp-content/uploads/2014/03/shood-460x295.jpg" style="border-style: none; vertical-align: top; max-width: 100%; height: auto; width: 144px; display: block;" /></a></li>
                            </ul>
                        </div>
                        <div class="recent-posts-content">
                            <h4 style="margin: 0px 0px 3px; font-family: MuseoSlab500Regular, arial, helvetica, sans-serif; color: rgb(51, 51, 51) !important; font-weight: normal; font-size: 13px !important; line-height: 20px !important;"><a href="http://www.lakmefashionweek.co.in/lfw-sr-14/the-stylecracker-hood-event-was-a-creative-fashion-platform-at-the-pavilion-during-lakme-fashion-week-summerresort-2014/" style="text-decoration: none; color: rgb(51, 51, 51) !important;">The Stylecracker Hood Event was a Creative Fashion Platform at the Pavilion During Lakme Fashion Week Summer/Resort 2014</a></h4>
                        </div>
                    </article>
                    <article class="col clearfix" style="float: left; width: 193px; margin: 0px 0px 20px;">
                        <div class="flexslider floated-post-slideshow" style="margin: 0px 20px 0px 0px; padding: 0px; background-color: rgb(255, 255, 255); position: relative; zoom: 1; width: 144px; float: left; overflow: hidden; background-position: initial initial; background-repeat: initial initial;">
                            <ul class="slides" style="margin: 0px; padding: 0px; list-style: none; z-index: 1000; zoom: 1; display: block;">
                                <li style="display: list-item; -webkit-backface-visibility: hidden;"><a href="http://www.lakmefashionweek.co.in/uncategorized/archana-kochhar-jyotsna-tiwari-dazzled-at-lakme-fashion-week-summerresort-2014-with-their-glamorous-colourful-collections/" rel="" style="text-decoration: none; color: rgb(51, 51, 51) !important;">
                                    <img alt="Archana Kochhar &amp; Jyotsna Tiwari Dazzled at Lakme Fashion Week Summer/Resort 2014 With Their Glamorous Colourful Collections" src="http://www.lakmefashionweek.co.in/wp-content/uploads/2014/03/feat28-460x295.jpg" style="border-style: none; vertical-align: top; max-width: 100%; height: auto; width: 144px; display: block;" /></a></li>
                            </ul>
                        </div>
                        <div class="recent-posts-content">
                            <h4 style="margin: 0px 0px 3px; font-family: MuseoSlab500Regular, arial, helvetica, sans-serif; color: rgb(51, 51, 51) !important; font-weight: normal; font-size: 13px !important; line-height: 20px !important;"><a href="http://www.lakmefashionweek.co.in/uncategorized/archana-kochhar-jyotsna-tiwari-dazzled-at-lakme-fashion-week-summerresort-2014-with-their-glamorous-colourful-collections/" style="text-decoration: none; color: rgb(51, 51, 51) !important;">Archana Kochhar &amp; Jyotsna Tiwari Dazzled at Lakme Fashion Week Summer/Resort 2014 With Their Glamorous Colourful Collections</a></h4>
                        </div>
                    </article>
                </div>
            </section>
        </div>
        <p style="margin: 0px; padding: 0px;">
            <br />
        </p>
        <p style="margin: 0px; padding: 0px;">
            &nbsp;</p>
        <br /> 
    </div>
&nbsp; <br /> <br /> <br /> <br /> <br /> <br /> <br />
    <br /> <br /> <br /> <br /> <br /> <br /> <br />


</asp:Content>


